### ISSUE TITLE
Build HelloExpress example failed because of git clone a package called Result

### ISSUE THREAD

**Issue by learningpro** [crossroadlabs/Express#27] opened 2016-04-16 13:05 UTC
I do just as the document said, write a Package.swift
import PackageDescription

let package = Package(
    name: "HelloExpress",
    dependencies: [
        .Package(url: "https://github.com/crossroadlabs/Express.git", majorVersion: 0, minor: 3),
    ]
)

but when I run ./build   , it clones many repo and finally failed with a message called

error: Failed to clone https://github.com/antitypical/Result.git
Packages/Result' already exists and is not an empty directory.

I want to know why there are so many packages even the Package.swift uses only one, and why the Reault package comes into failure.

**Comment by dileping** [comment] 2016-04-16 13:47
@learningpro Thanks a lot for reporting the issue. Most probably it's just some kind of dependency hell caused by recent release of Result 2.0.

Anyways we are preparing a release of version 0.4, which is fully compatible with Swift 3.0 and 2.2 simultaneously and uses brand new asynchronous model, including own new Futures library.

Consider, please, playing with Package.swift included in Express. If you succeed I will be happy to create a new intermediate release of 0.3.x.

**Comment by dileping** [comment] 2016-04-18 19:44
Resolved in new minor release

**Closed as completed by dileping** 2016-04-18 19:44 UTC
